// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kovmtspchvtcwysxibiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvdm10c3BjaHZ0Y3d5c3hpYml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTQ3NDEsImV4cCI6MjA3MjU5MDc0MX0.uzGqOSN-bykf140o-VPsKdv6-pBalxGqvEGJmRSPS4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});